# Generated by Django 3.1.3 on 2020-11-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
