# Generated by Django 3.1.3 on 2020-11-15 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_service_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='limit',
            new_name='traffic',
        ),
    ]
