# Generated by Django 3.1.3 on 2020-11-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201115_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='service',
            name='static_ip',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='traffic',
            field=models.BigIntegerField(default=0),
        ),
    ]
